# shell
shell zsh
shell_integration enabled no-cursor
# theme
include themes/insanity.conf

# font
font_family JetBrainsMono Nerd Font
# font_family DejaVu Sans Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 10
disable_ligatures cursor

# performance
repaint_delay    10
input_delay      0
sync_to_monitor  yes

# windows
enable_audio_bell no
visual_bell_duration 0
window_alert_on_bell no
# hide_window_decorations true
confirm_os_window_close 0
remember_window_size no
window_margin_width 0
placement_strategy top-left

# remote control (restricted to local socket instead of wide open)
allow_remote_control socket-only
listen_on unix:/tmp/kitty

# Keep the terminal visually minimal.
window_padding_width 0

# Do not animate terminal startup.
startup_session none

# Don't phone home for updates.
update_check_interval 0

# scrollback
scrollback_lines 10000

# cursor
cursor_shape block
# cursor_trail 1
cursor_blink_interval 0

# hides the mouse when typing
mouse_hide_wait 3.0

# transparency
background_opacity 1
dynamic_background_opacity no

# clipboard
clipboard_control write-clipboard write-primary no-append
copy_on_select no
strip_trailing_spaces smart
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# mappings
map ctrl+equal  change_font_size all +1.0
map ctrl+minus  change_font_size all -1.0
map ctrl+0      change_font_size all 0
map f11         toggle_fullscreen

# map ctrl+shift+equal set_background_opacity +0.05
# map ctrl+shift+minus set_background_opacity -0.05
# map ctrl+shift+0 set_background_opacity default

map ctrl+shift+f5 load_config_file

map ctrl+shift+e open_url_with_hints
map ctrl+shift+p>f kitten hints --type path --program -   # insere o path no prompt
map ctrl+shift+p>h kitten hints --type hash --program -   # hashes do git
map ctrl+shift+p>l kitten hints --type line --program -
map ctrl+shift+p>n kitten hints --type linenum            # abre arquivo:linha no editor

url_style single
