# shell
shell zsh
shell_integration enabled
term xterm-256color

# theme
include themes/insanity.conf

# font
font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 10
disable_ligatures never

# performance
repaint_delay    10
input_delay      2
sync_to_monitor  yes

# windows
enable_audio_bell no
visual_bell_duration 0
window_alert_on_bell no
# hide_window_decorations true
confirm_os_window_close 0
remember_window_size no
window_margin_width 0

# remote control (restricted to local socket instead of wide open)
allow_remote_control socket-only
listen_on unix:/tmp/kitty

# Keep the terminal visually minimal.
window_padding_width 0

# Do not animate terminal startup.
startup_session none

# Don't phone home for updates.
update_check_interval 0

# scrollback
scrollback_lines 10000

# cursor
cursor_shape block
# cursor_trail 1
cursor_blink_interval 0

# clipboard
clipboard_control write-clipboard write-primary no-append
copy_on_select yes
strip_trailing_spaces smart
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# mappings
map ctrl+equal  change_font_size all +1.0
map ctrl+minus  change_font_size all -1.0
map ctrl+0      change_font_size all 0
map f11         toggle_fullscreen

map ctrl+alt+k scroll_line_up
map ctrl+alt+j scroll_line_down
map ctrl+shift+k scroll_page_up
map ctrl+shift+j scroll_page_down

