# Black Metal (Gorgoroth)
# Base16 - metalelf0

background #000000
foreground #c1c1c1

cursor #b0b0b0
cursor_text_color #000000

selection_background #222222
selection_foreground #c1c1c1

url_color #888888

# ANSI colors

# black
color0 #000000
color8 #333333

# red
color1 #5f8787
color9 #5f8787

# green
color2 #9b8d7f
color10 #9b8d7f

# yellow
color3 #8c7f70
color11 #8c7f70

# blue
color4 #888888
color12 #999999

# magenta
color5 #999999
color13 #999999

# cyan
color6 #aaaaaa
color14 #444444

# white
color7 #c1c1c1
color15 #c1c1c1

# Kitty UI

active_border_color #585858
inactive_border_color #222222

bell_border_color #5f8787

active_tab_foreground #707c71
active_tab_background #262626

inactive_tab_foreground #808080
inactive_tab_background #000000

tab_bar_background #000000
